[package]
name = "wasm-debug-symbols"
version = "0.1.0"
authors = ["art-in <artin@artin.space>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.57"

[package.metadata.wasm-pack.profile.dev.wasm-bindgen]
dwarf-debug-info = true